### PR TITLE
Fix for issue 16 froala-react

### PR DESCRIPTION
**Pull request by sharma-dark-knight**

### CODE REVIEW

**Comment by jyhong666** [comment]
Help! I Can't run it under typescript!

I use it by https://github.com/froala/react-froala-wysiwyg#using-type-definition-file

but I can't run it!

could you give me a sample or demo?

thank you a millon!

**Comment by sharma-dark-knight** [comment]
Hi  jyhong666
It seems you are using create-react-app to create typescript project.
Please follow below steps.
1. import $ from 'jquery';
 (window as any).$ =$;
 ReactDOM.render(<FroalaEditor/>, document.getElementById('root'));

Use above lines in your js file.
2.Create index.d.ts(attached)  file in your react-froala package and put below lines:

import React from 'react';

export interface MyComponentProps {
   tag?:string;
   config?: object;
   model?: string| object|null;
   onModelChange?: function;
   onManualControllerReady?: function;
}


declare class  FroalaEditor extends React.Component<MyComponentProps>{
   destroy():void;
   getEditor(): any;
   initialize() : object;
}
export default FroalaEditor;

declare class  FroalaEditorInput extends React.Component<MyComponentProps>
{

}
export default FroalaEditorInput;

declare class  FroalaEditorView extends React.Component<MyComponentProps>
{

}
export default FroalaEditorView;

declare class  FroalaEditorButton extends React.Component<MyComponentProps>
{

}
export default FroalaEditorButton;

declare class  FroalaEditorImg extends React.Component<MyComponentProps>
{

}
export default FroalaEditorImg;
declare class  FroalaEditorInput extends React.Component<MyComponentProps>
{

}
export default FroalaEditorInput;

declare class  FroalaEditorA extends React.Component<MyComponentProps>
{

}
export default FroalaEditorA;

**Comment by jyhong666** [comment]
> Hi  jyhong666
> It seems you are using create-react-app to create typescript project.
> Please follow below steps.
> 1. import $ from 'jquery';
>  (window as any).$ =$;
>  ReactDOM.render(<FroalaEditor/>, document.getElementById('root'));
> 
> Use above lines in your js file.
> 2.Create index.d.ts(attached)  file in your react-froala package and put below lines:
> 
> import React from 'react';
> 
> export interface MyComponentProps {
>    tag?:string;
>    config?: object;
>    model?: string| object|null;
>    onModelChange?: function;
>    onManualControllerReady?: function;
> }
> 
> 
> declare class  FroalaEditor extends React.Component<MyComponentProps>{
>    destroy():void;
>    getEditor(): any;
>    initialize() : object;
> }
> export default FroalaEditor;
> 
> declare class  FroalaEditorInput extends React.Component<MyComponentProps>
> {
> 
> }
> export default FroalaEditorInput;
> 
> declare class  FroalaEditorView extends React.Component<MyComponentProps>
> {
> 
> }
> export default FroalaEditorView;
> 
> declare class  FroalaEditorButton extends React.Component<MyComponentProps>
> {
> 
> }
> export default FroalaEditorButton;
> 
> declare class  FroalaEditorImg extends React.Component<MyComponentProps>
> {
> 
> }
> export default FroalaEditorImg;
> declare class  FroalaEditorInput extends React.Component<MyComponentProps>
> {
> 
> }
> export default FroalaEditorInput;
> 
> declare class  FroalaEditorA extends React.Component<MyComponentProps>
> {
> 
> }
> export default FroalaEditorA;
> …

Great!

I did it!

I really appreciate what you've done for me.

**Comment by jyhong666** [comment]
I'm sorry to bother you again, pls help me,thanks!

As we need the Style tag, I added the htmlRemoveTags: ['script'] and iframe: true,  option,  But when I add these option, the preview doesn't show all the information.

The following steps allow you to reproduce the problem
step1:Click on the below link
https://www.froala.com/wysiwyg-editor/examples/adjustable-height
step 2: Click the "Edit in JSFiddle"  to jump to the JSFiddle page 
$('div#froala-editor').froalaEditor({
 htmlRemoveTags:['script'],
 iframe: true
})

step 3:Put the html code in the attachment in the FroalaEditor on the right.
Then click CodeView, to the bottom of the content can not be displayed. However, the full screen can be displayed.


We have a similar problem in our project.

Thank you!
[froalaEditorTest.txt](https://github.com/dheerajaccolite/react-froala-wysiwyg/files/3025325/froalaEditorTest.txt)

**Pull request merged**
